# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b4ee8e10ad50aede94abcd68853ba59311d606d0f9c7eacbe9a29e6f32ef0a148a90e37696d5ca6c283f188cf374408e290d1c9993f1c916ff20a09e975a7a1

test:
  secret_key_base: d86caeb959ce3b48596c37a12914d5263f376b4a9fa8eddc014d1916a350dcada81c4cda7c65b0f01347400ec41962d54a52337dddcd2e0ad34f9ebf3fcdb9fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
